### ISSUE TITLE
Error: Failed to instantiate provider "keycloak" to obtain schema: exec: "C:\\terraform\\terraform-provider-keycloak": file does not exist

### ISSUE THREAD

**Issue by HediTun77** [mrparkers/terraform-provider-keycloak#258]
Hello,
I Installed Go into my machine and the visual code go extension. I succeed to build the go project, the build cmd  generate a "terraform-provider-keycloak" file, I add the generated file to terraform folder and under "terraform.d\plugins\windows_amd64". The "Terraform init" cmd is Ok, but when I execute Terraform validate I got the following error :
Error: Failed to instantiate provider "keycloak" to obtain schema: exec: "C:\\terraform\\terraform-provider-keycloak": file does not exist.

Thanks for Help

**Comment by mrparkers** [comment]
Hi @HediTun77.  I'm sorry that this isn't working for you.  Unfortunately, I am not sure that I will be of much help since I'm not a Windows user.

Could you try using one of the pre-built binaries available on the [releases page](https://github.com/mrparkers/terraform-provider-keycloak/releases) and see if that works for you?

**Comment by HediTun77** [comment]
Thank you mrparkers. In fact I resolve it by adding the ".exe" extension to the "terraform-provider-keycloak" file ====> "terraform-provider-keycloak.exe". That's all. Actually Im facing another issue when I execute plan cmd. I will create a new issue for it. Thanks

**Comment by HediTun77** [comment]
Renaming the "terraform-provider-keycloak" file to "terraform-provider-keycloak.exe" for windows
