### ISSUE TITLE
creating resource keycloak_user with federated_identity fails with keycloak >= 9

### ISSUE THREAD

**Issue by zauberpony** [mrparkers/terraform-provider-keycloak#291]
Hey, first of all thanks for your work!

Creating users with federated_identity set fails for keycloak > 9 with the following message:

```
Error: error sending POST request to /auth/admin/realms/my-realm/users/df4e64ba-5fbc-4842-b160-79b2f13d2e51/federated-identity/google: 409 Conflict

  on main.tf line 11, in resource "keycloak_user" "my_user":
  11: resource "keycloak_user" "my_user" {
```

Basically https://github.com/mrparkers/terraform-provider-keycloak/blob/master/keycloak/user.go#L43-L46 fails for keycloak >= 9, since https://github.com/mrparkers/terraform-provider-keycloak/blob/master/keycloak/user.go#L36 already creates the federated_identity, thus the conflict.

Terraform snippet that reproduces the issue:
```
resource "keycloak_realm" "my_realm" {
  realm = "my-realm"
}

resource "keycloak_oidc_google_identity_provider" "realm_identity_provider" {
  realm         = keycloak_realm.my_realm.realm
  client_id     = "random-id.apps.googleusercontent.com"
  client_secret = "random-secret"
}

resource "keycloak_user" "my_user" {
  realm_id = keycloak_realm.my_realm.id
  username = "my_user"

  federated_identity {
    identity_provider = "google"
    user_id           = 123456789
    user_name         = "my_user@example.com"
  }
}
```

**Comment by tomrutsaert** [comment]
Thanks for the report, good find.
Temp workaround, first create the user, then add the federate identity....

Good that keycloak changed this behavior so drastically.... :confused: 
So before version 9, It ignored the federated identity when you did a POST to create a new user. You need to do an explicit call to add the federated identities.
Starting version 9 it does look at the federated identities and creates them. So you may not do the extra calls any more --> they return a 409 conflict.

Anyway I think, I will need to fall back on first deleting the federating identities after creating the user, to add them immediately again.
Otherwise we need to build in some check on keycloak version, to know how to create these federated identities in all cases.

**Comment by zauberpony** [comment]
Well, instead of deleting the federating identity, you could check if they have been created/are available.
Or, remove the `federatedIdentities` from the `user` when doing the initial post.

Both solutions (and some others one could think of like e.g., just ignore 409 etc.) feel hacky.

Maybe it could be a solution to define the (major) keycloak-version in the provider, and then the keycloakClient can execute different requests based on the version if required?

If you have a preferred solution I could try to fix this and open a PR, if you want me to…

**Comment by tomrutsaert** [comment]
The extra  "funny" thing is, this behavior is only changed when creating new users. 
When updating a user, the federated identities are ignored in the PUT call and you need to make the extra call to update the federated identities :unamused:

**Comment by tomrutsaert** [comment]
I will make a PR, I am already toying with this code

**Comment by tomrutsaert** [comment]
As you hinted, removing the fed identities from the initial post seems to be the cleanest way to do it, It should work in any circumstance.

**Comment by tomrutsaert** [comment]
Fixed, should come with next release

**Comment by zauberpony** [comment]
Just tested with master, I can confirm that it works. Great job, Thank you very much!
