### ISSUE TITLE
Trying to delete a currently active flow bindings results in 500

### ISSUE THREAD

**Issue by svenstaro** [mrparkers/terraform-provider-keycloak#297]
So when you make a new Browser Flow "My Flow" and then choose it as a `browser_flow = "My Flow"` and then delete "My Flow", the operation will fail with 500. Apparently you can't delete a flow that's in use. While I think this should definitely be handled by Keycloak itself, in the meantime, how about when deleting a flow that's in use by a flow binding, you first change back the flow to its respective default (in this case that'd be the "browser flow") in order to make sure that we don't run into 500s?

**Comment by mrparkers** [comment]
I think the best we can do in this situation is make the error message more clear.  It makes sense that Keycloak would return a 500 when you try to delete a flow that's in use, and I think it's a better user experience to present this error back to the user, rather than the provider working around it and modifying another resource that you didn't expect it to.

I'm happy to keep this issue open so we remember to make this more clear in the future, but I don't want to change the way this is currently working.

**Comment by dembaca** [comment]
I have a related problem: When defining additional `keycloak_authentication_flow` resources you need to provide a `realm_id`, so the resources can be created successfully within the realm. However, if you refer to a custom flow in the `keycloak_realm` resource like above, the realm creation fails, because the custom flows do not yet exist. So this is a chicken-and-egg problem.

I was thinking if it could make sense to implement the flow bindings as separate resources with their own state to circumvent cyclic reference problems. Not sure, if it helps to resolve the situation above, but I cannot find a solution with the current implementation to setup a greenfield realm with custom authentication flows in just one terraform run.

**Comment by tomrutsaert** [comment]
@dembaca , It is a known issue: see #298
