### ISSUE TITLE
Merge with https://github.com/tazjin/terraform-provider-keycloak?

### ISSUE THREAD

**Issue by cthiebault** [mrparkers/terraform-provider-keycloak#34]
Hello
Thanks for the great work you did on Terraforming Keycloak!!!
It's too bad to have 2 providers covering different parts of Keycloak instead of one with better coverage...

Is there a reason why you didn't go with https://github.com/tazjin/terraform-provider-keycloak?
It seems to be existing since a moment now...

Cedric

**Comment by mrparkers** [comment]
Hi @cthiebault

I decided against using the existing provider because it was mentioned in https://github.com/tazjin/terraform-provider-keycloak/pull/24 that it was no longer actively maintained.    I wanted to be able to work on this provider at my own pace and not be held up by the lack of merge rights, and I also wanted to set up acceptance tests and CI, which would have required some owner permissions.  I figured it was easier to create my own repo for it.

I'll happily backfill any features from the other provider to this one.  Feel free to open an issue with any requests you might have.

**Comment by cthiebault** [comment]
Thanks @mrparkers for your explanation!
I didn't know that the other repo was no longer maintained...

I'll create issues for feature I would like to use... and I'll try to contribute to this repo ;-)

**Comment by mrparkers** [comment]
Sounds great!  Please open an issue if you want to work on something and have any questions for me :smile:

Just so you know, I only have a couple more resources to implement before I release 1.0.0, which should make using the provider easier, since I will have some built binaries ready to download and use.

I'm going to close this issue since I think your original question has been answered.
