### ISSUE TITLE
Assign Required Actions to Users/Group

### ISSUE THREAD

**Issue by timbmg** [mrparkers/terraform-provider-keycloak#341]
As per #131 required actions can be defined.

Can these be assigned to a user resource? I am thinking of something like this:

```terraform
resource "keycloak_realm" "realm" {
    realm = "test"
}

resource "keycloak_required_action" "terms_and_conditions" {
  realm_id       = keycloak_realm.realm.id
  alias          = "terms_and_conditions"
  default_action = false
  enabled        = true
  name           = "Terms and Conditions"
}

resource "keycloak_user" "user" {
  realm_id            = keycloak_realm.realm.id
  username            = "test-user"
  enabled             = true
  required_action_ids = [keycloak_required_action.terms_and_conditions.alias] 
}

```

According to the Keycloak docs this should be possible via the API.
The user resource takes a list of strings for required actions. See here: https://www.keycloak.org/docs-api/10.0/rest-api/index.html#_userrepresentation

**Comment by tomrutsaert** [comment]
I might be mistaken, but this does not make any sense to me.
Terraform is to handle state. In this case the state of keycloak.
By setting this required action, it would be re-set every time again, even if the user has completed the required action.
Because setting a required action is a temporary thing a user needs to do at the next login.
Once a user has done the required action, the required action goes away.
The Keycloak Admin UI states the same:

![image](https://user-images.githubusercontent.com/13900759/86931935-00dcfa00-c139-11ea-8d23-ca4f71fb3299.png)

What do you think?
Am I missing something?

**Comment by timbmg** [comment]
Yes good point, that of course would not desired.

I tried to set my required action as default action, so the newly created users should have them. But that did not work.

**Comment by tomrutsaert** [comment]
That should work. Did you enable the required action as well?
Are both checkboxes checked when you verify it via the admin ui?
At least the UI docs state that this is the intention.
![image](https://user-images.githubusercontent.com/13900759/86937311-62a06280-c13f-11ea-9a50-8521da9108a4.png)

**Comment by timbmg** [comment]
Yes, it's enabled and default action is also set.

I just tried to add an user via the admin UI, there the default actions are automatically added when creating the user.

**Comment by timbmg** [comment]
Might this be due to the order the resources are created?

**Comment by timbmg** [comment]
Indeed that was the problem.
I added a `depends_on` on the required_action, and it worked out.
