### ISSUE TITLE
apply on keycloak_realm resource overrides non-managed token list-element attributes without showing changes

### ISSUE THREAD

**Issue by arkesan** [mrparkers/terraform-provider-keycloak#346]
Good morning,

when i make changes on the keycloak_realm resource, for example change the token `sso_session_idle_timeout`, the provider (or the keycloak api) overrides the attributes from the list element `Default Signature Algorithm` and `Override User-Initiated Action Lifespan ` with null (?) values. This attributes are not implemented in the keycloak provider and terraform does not show changes on this elements by `terraform apply` and `terraform plan`.

![image](https://user-images.githubusercontent.com/68268916/87764239-58085c00-c816-11ea-9a3a-3a38b5bd7756.png)

![image](https://user-images.githubusercontent.com/68268916/87764369-8b4aeb00-c816-11ea-9a96-6746c82e85fc.png)

In general it would be an enhancement to extend the provider with this attributes, but in this case its bug.

I have test it with the provider version `1.16.0` and `1.19.0` on Keycloak `10.0.x`

best regards

**Comment by tomrutsaert** [comment]
I would state that when something is managed by terraform, it should not be manipulated via the ui. 
As a realm resource is managed via 1 PUT call, it seems logical that the provider does not send any value for fields not declared in the terraform config. So IMHO this not a bug, it is just a not supported field.

That being said: you could add those fields to the attributes field of the realm resource.
Attributes are just passed along to keycloak. This is to support custom realm extensions. But it can also be used for unsupported (new) fields.
Be aware the moment someone builds support for those (new) fields, you need to migrate, because the value in attributes will be ignored.

example: 

```
resource "keycloak_realm" "realm" {
    realm                   = "test"
    enabled                 = true
    attributes = {
      mycustomAttribute = "myCustomValue"
      defaultSignatureAlgorithm = "ES256
    }
```

The key and value corresponds with the key and value the keycloak ui  "save" call sends to keycloak backend. Look at the network traffic in your browser for the PUT call /auth/admin/realms/myrealm
So you can look what the value and key would be for "Override User-Initiated Action Lifespan"

**Comment by arkesan** [comment]
Ahh thanks! I dont know i can handle attributes this way. I will checko it out.
