### ISSUE TITLE
Error: unsupported attribute "federated_identities"

### ISSUE THREAD

**Issue by cthiebault** [mrparkers/terraform-provider-keycloak#378]
- Keycloak 8.0.2
- Terraform 0.13.0
- registry.terraform.io/mrparkers/keycloak v2.0.0-rc.0

After upgrading Terraform & providers, running `terraform plan` returns   
`Error: unsupported attribute "federated_identities"`.  

It was working with Terraform 0.12 & Keycloak provider 1.18.

Log with trace enabled shows:
```
2020/09/03 09:11:07 [TRACE] vertex "module.keycloak.keycloak_openid_client_service_account_role.xxx (expand)": entering dynamic subgraph
2020/09/03 09:11:07 [ERROR] eval: *terraform.EvalSequence, err: unsupported attribute "federated_identities"
```

**Comment by mrparkers** [comment]
This is one of the "breaking" changes that I haven't gotten the chance to document yet since I haven't released v2.0.0 yet.  This used to be a property on `keycloak_openid_client_service_account_user` data source, but the provider code was trying to set an attribute called `federated_identity` instead (since this is what the attribute is called for the `keycloak_user` resource).

So this isn't a huge change because the old attribute was never being set correctly regardless.

Can you try to update your usage to `federated_identity` instead?  I could also update the code to formally deprecate this attribute, but I didn't think that was necessary since the old one was broken anyways.

**Comment by cthiebault** [comment]
Thanks for your help!

Here is my `keycloak_openid_client_service_account_user` usage:
```
data "keycloak_openid_client_service_account_user" "user-service" {
  client_id = keycloak_openid_client.user-service.id
  realm_id = keycloak_realm.xxx.id
}
```

I don't use `federated_identity` property...

**Comment by mrparkers** [comment]
Hey @cthiebault, can you give v2.0.0 a try and see if this issue is resolved?

**Comment by cthiebault** [comment]
It works now!
Thanks for your great work @mrparkers !!
