### ISSUE TITLE
Problem with the declaration of a module during "terraform init"

### ISSUE THREAD

**Issue by Noann35** [mrparkers/terraform-provider-keycloak#395]
Hello everyone, 

I created a Docker image integrating the keycloak provider 2.0.0.
I declare my resources (realm, client ...).
Everything is OK, "terraform init" is successful : 

Below is the configuration file "poc-terraform-keycloak/main.tf" without the "provision" module : 
![image](https://user-images.githubusercontent.com/14089741/95205716-0d2f2c80-07e6-11eb-9b20-c825e8d784cd.png)

Below is this trace in successful :
![image](https://user-images.githubusercontent.com/14089741/95206026-79aa2b80-07e6-11eb-8f72-9e0ed4844990.png)

**Wanting to apply these resources on several environments, I thought of using a "provisioning-keycloak" module for example.**
**But the "terraform init" fails.
I cannot understand the problem.**

Below is the tree structure of my "poc with the "provision" module : 
![image](https://user-images.githubusercontent.com/14089741/95196073-c803fe00-07d7-11eb-8279-34cb89685104.png)

Below is the configuration file "poc-terraform-keycloak/main.tf" with the declaration of the keycloak provider and the module : 
![image](https://user-images.githubusercontent.com/14089741/95204479-701fc400-07e4-11eb-89a9-ca18c71f970c.png)

The resources declared in the module at "poc-terraform-keycloak/modules/provision/main.tf" are correctly entered:
![image](https://user-images.githubusercontent.com/14089741/95204954-0a800780-07e5-11eb-9a22-40ae497a82e1.png)

But when I run a "terraform init", I have this trace:
![image](https://user-images.githubusercontent.com/14089741/95205299-7b272400-07e5-11eb-9144-4f07e5641b03.png)

**I don't understand where the problem is coming from, does anyone have any idea please?
Is it an error in my configuration, a Terraform bug, a keycloak provider bug ?**

**Comment by mrparkers** [comment]
In order to use third party providers within a module, the same `terraform.required_providers` block that you included in your root `main.tf` file must also be present within the module configuration.  I'm not a fan of this behavior, since official providers don't make you do this, but there's nothing I can do about it unfortunately.

See https://github.com/hashicorp/terraform/issues/25984 for more context on this.

Also, instead of using the source of `terraform.local/providers/keycloak`, you can automatically download the Keycloak provider from the Hashicorp registry by using this instead:

```hcl
terraform {
  required_providers {
    keycloak = {
      source  = "mrparkers/keycloak"
      version = ">= 2"
    }
  }
}
```

Anyways, let me know if this helps with the issue you're having.

**Comment by Noann35** [comment]
@mrparkers 
A big thank you for this release, it works wonderfully.
I was aware of the recent provisioning via the Hashicorp registry, but unfortunately I cannot use an external registry.

**Comment by rymir** [comment]
@mrparkers I'm not getting the reason why this behaviour isn't just an "opt-in" though, overriding the non-default 3rd party providers in the root child modules whenever there's a need to do so and otherwise going forward with the source/version declared in the root?

In our case, we have hundreds of terraform states and hundreds of terraform modules. Explicitly configuring the defaults throughout the codebase feels unnecessary, given that we always stick with the root versions compatibility.

**Comment by mrparkers** [comment]
@rymir yeah, I agree with you.  I also wish there was a way for modules to inherit provider versions from the root.  Unfortunately, there's nothing I can do within this provider to change that.  This behavior would have to be changed in Terraform core.

I'm gonna go ahead and close this issue since it appears that the original problem was resolved.  Thanks for the discussion everyone!
