### ISSUE TITLE
[auth flow] lack of prority on keycloak_authentication_execution despite available into JSON export

### ISSUE THREAD

**Issue by semangard** [mrparkers/terraform-provider-keycloak#412]
Hello,

When exporting a realm JSON, there is a priority for a _keycloak_authentication_execution_

![image](https://user-images.githubusercontent.com/57065741/97068590-26e3b880-15c9-11eb-8b33-524ed630aeb7.png)

Could you please add it to https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs/resources/authentication_execution

PS: I do not see the added value of the _depends_on_

**Comment by semangard** [comment]
I we try to add it we get the error ::

```
Error: Unsupported argument

  on commons/modules/flows/kerberos/main.tf line 14, in resource "keycloak_authentication_execution" "kerberos_cookie":
  14:   priority          = 10
```

**Comment by semangard** [comment]
It is created like that ::

![image](https://user-images.githubusercontent.com/57065741/97068699-4d562380-15ca-11eb-89a0-5179cf59a09a.png)

**Comment by tomrutsaert** [comment]
Yeah, That is not how the admin api works. There is only a 'Lower Priority' and 'Raise Priority' rest endpoint.
And there is no way to set the priority directly.
see: https://www.keycloak.org/docs-api/11.0/rest-api/index.html#_authentication_management_resource
There have been many discusions about this in the past and this is just the pragmatic solution for the time I had available.
I am always open for suggestions or pull requests on how to make this better. 

see for more info here in the old pull requests:

https://github.com/mrparkers/terraform-provider-keycloak/pull/138
and
https://github.com/mrparkers/terraform-provider-keycloak/pull/215

The reason depends_on is needed is because keycloak will add the execution in the order you create them, So by using depends_on you can influence the priority/order
