### ISSUE TITLE
[auth flow] keycloak_authentication_execution_config   : failure when the config key is not quoted => improve doc to avoid mistakes

### ISSUE THREAD

**Issue by semangard** [mrparkers/terraform-provider-keycloak#413]
Hello,

a) This does not work ::
![image](https://user-images.githubusercontent.com/57065741/97082392-a0030000-1609-11eb-8034-989880e7f370.png)

We go the error ::

```
Error: Reference to undeclared resource
  on commons/modules/flows/first-broker-login/safe-idp/main.tf line 25, in resource "keycloak_authentication_execution_config" "hug_1st_safe_idp_login_flow_review_profile_config":
  25:                 update.profile.on.first.login = "missing"

```

b) This works ::

![image](https://user-images.githubusercontent.com/57065741/97082385-8c579980-1609-11eb-9b5e-2bb1765c08cf.png)

==> The examples given at 
https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs/resources/authentication_execution_config  
or
https://github.com/mrparkers/terraform-provider-keycloak/blob/master/example/main.tf
should use quote

**Comment by tomrutsaert** [comment]
Not really a bug of the this provider, is it.
you are referening a dynamic config variable that has dots in its name.
AFAIK I know dots do not work anywhere in a variable name in tf config, because terraform interprets the dots and therefore you have use double quotes around them.
The examples in documentation and main.tf do not use a config variable name with dots ( _defaultProvider_ ) and thus are perfectly fine without double quotes.
