### ISSUE TITLE
Configuring keycloak realm results in timeout failure

### ISSUE THREAD

**Issue by RubenAtPA** [mrparkers/terraform-provider-keycloak#467]
We want to configure the keycloak deployment using this provider. However it fails every time with a timeout error. We've already tried setting the `TF_REGISTRY_CLIENT_TIMEOUT` value to 30 seconds, but it already fails long before that. The problem is that the realm itself has been created and when running the plan/apply again it fails because of a conflict.

```
module.k8s-objects.keycloak_realm.spend-cloud-realm: Creating...
Error: error sending request: Post "https://oauth.*******/auth/admin/realms": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

How can this be resolved?

OS image: google/cloud-sdk:alpine
Cloud Provider: GCP
Terraform version: 0.12.5
Keycloak provider version: 2.0.0
Keycloak Server version: 12.0

**Comment by kaveenr** [comment]
I'm getting the same Issue as well :(

**Comment by mrparkers** [comment]
Hey @RubenAtPA and @kaveenr - sorry about the issue you're having.

Just so I understand, your issue is that the realm creation takes too long, causing the provider to time out, and a follow-up plan/apply to fail with a 409 conflict?

For the first issue, you can try setting the [`client_timeout`](https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs#client_timeout) provider attribute, which will cause the provider to wait for a longer period of time before timing out a request.  The default is 5 seconds, which I think is probably too short anyways, so I may increase that default in a future release.

For the second problem, if the realm already exists and isn't in your Terraform state, you can use `terraform import` to persist the realm into your state so a following apply will not attempt to recreate the realm.

Let me know how this works for you.  Thanks!

**Comment by mrparkers** [comment]
I went ahead and increased the default timeout in #469

**Comment by RubenAtPA** [comment]
Thanks @mrparkers. 
We configured it with 30 seconds, just be safe, and it did seem to work a lot better now. We do still have one issue left, but I think that is something that should be in it's own issue. 

The provider is highly dependent on the existence of the keycloak server deployment and it will fail if it's not there. Within our terraform however we also configure the deployments, including the one for keycloak, but providers are loaded before that. This results in a failure unfortunately. If it's possible for the service configuration check to be done at a later stage, and thus not in the provider, that would be helpful. Is that possible and shall I make a new issue for that?

**Comment by mrparkers** [comment]
Have you tried setting the `initial_login` provider attribute to `false`?  This delays the provider initialization until the first time Terraform attempts to create a resource or read from a data source.  It was added specifically so you could deploy Keycloak using something like the `helm_release` resource, and then configure Keycloak using this provider, all in one run of `terraform apply`.

**Comment by RubenAtPA** [comment]
Hi @mrparkers . We've tried with the setting and it does wait for the login with initializing the provider, however the problem seems to be deeper. In our Terraform we configure our Keycloak Server deployment simultaneously with the configuration. The problem is however that the initial deployment can take some time for the first configuration and the API isn't ready to accept requests. Is it possible for the Terraform provider to wait with the configuration as long as the Keycloak server isn't ready yet?

**Comment by mrparkers** [comment]
Unfortunately, there isn't really good a way for the provider to wait for the Keycloak server to be ready before attempting to interact with its API.  This is really a symptom of how the Terraform code is structured, or rather, how Terraform works when deploying some software and then later configuring that software.

This use case is why I personally run Terraform using [Terragrunt](https://terragrunt.gruntwork.io/), which is a thin wrapper around Terraform.  Terragrunt allows me to define my configuration within different stages, so it's very explicit that the code that installs software runs before the code that configures the software.

As an example, I have a stage that I call `apps`, which uses the Helm Terraform provider with the `helm_release` resource to install things like Vault or Keycloak to my Kubernetes cluster.  Then, I use a stage called `config`, which uses the Keycloak and Vault Terraform providers to further configure them.  The `config` stage depends on the `apps` stage, so running `terragrunt run-all apply` will know to apply the `apps` stage first.

You can see an example of how this works here: https://terragrunt.gruntwork.io/docs/features/execute-terraform-commands-on-multiple-modules-at-once/

I'm going to go ahead and close this, since the functionality you're looking for is out of scope for this provider, but feel free to let me know if you have any questions about how to solve this problem using something like Terragrunt.  If you don't want to use Terragrunt, a simpler solution would be to use the [`null_resource`](https://registry.terraform.io/providers/hashicorp/null/latest/docs/resources/resource) to run a local command like `sleep 300`, so you can wait an arbitrary amount of time for Keycloak to be provisioned.
