### ISSUE TITLE
Since version 3.0.0 extra_config parameter on the keycloak_oidc_identity_provider resource for fields syncMode and guiOrder is ignored

### ISSUE THREAD

**Issue by tomrutsaert** [mrparkers/terraform-provider-keycloak#520]
Since version 3.0.0 extra_config parameter on the keycloak_oidc_identity_provider resource for fields syncMode and guiOrder is ignored

Terraform still sees those fields in the tf files and still states (during planning) that it needs to add those fields to keycloak,
But it actually does not send it to keycloak api. Even worse, it removes previous set with version 2.3.0 values.
:-( I have now a whole qa environment without syncMode ="FORCE" and without guiOrder on all my idps :-(
This breaks old configs, I will need to revert to 2.3.0, I will try to look at a later time what could be the culprit

example config:

```
resource "keycloak_oidc_identity_provider" "my_idp" {
  realm                 = keycloak_realm.myrealm.id
  //other fields 

  extra_config = {
    syncMode         = "FORCE"
    guiOrder          =  "1"
  }
}
```

**Comment by tomrutsaert** [comment]
This is related to the change of @alex-hempel in #508 
![image](https://user-images.githubusercontent.com/13900759/115878545-f205d080-a448-11eb-9ef7-0050aae84a04.png)

You can not add fields for only one of the type of idp providers.
If you add missing fields they should be added in all corresponding idp resources.
The Marshal/unmarshal methods contain logic that prevents from setting fields via extra config, if a field is defined as a normal field.
Besides the resource keycloak saml identity provider, we have the resource keycloak oidc identity provider, google, custom, ....
All these need to be tackled, as in the current state these can not set anymore guiOrderand SyncMode

And when we add these fields to the relevant resources, we still need document this in release notes and normal docs, because it will break existing config. project will need to migrate extraConfig.guiOrder to gui_order and extraConfig.SyncMode to sync_mode.

Project that are currently using the  saml identity provider resource and one of those fields will need to migrate as well

I also see that this change is not reflected in the documentation for the saml identity provider, so people looking for these params in the docs, will also have no clue.

**Comment by tomrutsaert** [comment]
@mrparkers  @alex-hempel, What are your opinions on this topic?

**Comment by mrparkers** [comment]
Yeah this one is my fault - I merged that PR and was going to push up docs for it, but I stashed those changes some time ago then ultimately forgot about it.

For the compatibility issue, I think we can get around this by checking if either of these two properties are in `extra_config`, and manually setting `GuiOrder` and `SyncMode` on the updated model.  Unfortunately, we're constantly going to be running into problems like these whenever new properties are added to identity provider models that may have previously been set via `extra_config`.  So I'm not even sure if there's a way to gracefully handle this in the future.  The best option really would be to support every configuration option, but I'm afraid I don't have the context with these resources to do that confidently.

**Comment by mrparkers** [comment]
Looking at it some more - like you said, the best option is probably to move forward with updated documentation and a fixed changelog that calls this out as a breaking change to all identity provider resources.  I would really like to fully deprecate `extra_config` and support every possible configuration for all major identity providers to try and avoid this situation in the future.  I'd appreciate your thoughts on this @tomrutsaert - if I take on this work, is there something that I might be overlooking here that would require `extra_config` to remain as it is today?

In order to update the docs on the Terraform registry, I'll have to push out a release, so I think I may add a warning statement so that any usage of `extra_config["guiOrder"]` and `extra_config["syncMode"]` displays a clear warning in the logs.

I'm really sorry if this change broke anyone's Keycloak configuration.  I'll be extra careful going forward to not make this mistake again.

**Comment by alex-hempel** [comment]
I'll be honest here, this is the first time I've contributed to a project like this. The reason I made this PR is because my team had a specific need for the parameters `principalType` and `principalAttribute` in `keycloak_saml_identity_provider`. I was unaware that `guiOrder` and `syncMode` were included in `extra_config` and that the explicit addition of those parameters in one resource would also impact other resources. When there were no obvious problems in the tests, I assumed the change was working fine. I apologise sincerely for that oversight. 

Would a quick interim fix be to excise `GuiOrder` and `SyncMode` from `keycloak/identity_provider.go` and the corresponding bits from `provider/resource_keycloak_saml_identity_provider.go`, until such time as the proper deprecation of extra_config can be tackled, @mrparkers?

**Comment by mrparkers** [comment]
@alex-hempel I appreciate your response, but please don't feel the need to apologize.  It's my job to review PRs that are submitted and catch issues like these before they make their way into a release.  We get a lot of contributions from folks like you that are newer to Golang and Terraform provider codebases, and it's impossible to expect everyone to be intimately familiar with the intricacies that go along with it.  Especially with these identity provider resources, which are some of the more complicated ones.  So I don't want you or anyone else to be discouraged from future contributions, I just need to do a better job to catch stuff like this beforehand, or clean up the code a bit so it's clearer how a particular change will affect the provider.  And, as you correctly pointed out, clearly we are missing some test coverage for these resources, so there is definitely some room for improvement in a few places 😅 

As far as the fix goes, I'm working on it now, but I'll tag you on the PR I submit so you can see how I approached it.  I will most likely leave `extra_config` for now, and work on deprecating it in the future.

Again, I really appreciate the time you took to make a contribution here, even if it ended up causing a problem in this release.  I dropped the ball in my review, so I will accept the blame for any of the resulting issues.

**Comment by alex-hempel** [comment]
Thank you @mrparkers , I appreciate your response. And yes, please keep me up to date with the changes you're making, it's a good learning opportunity for me.

**Comment by tomrutsaert** [comment]
@alex-hempel, no worries, your contribution is highly appreciated, It is really a tricky issue, I had really go into the code to figure out what is going on. I was even aware in the past that might become an issue, I should have documented it somewhere
@mrparkers I saw the initial PR of Alex and although already worked on the this part of the code, I missed the catch/impact as well

Anyway. Extra config really needs to stay, I would even argue it needs to exist on every resource.
Any custom SPI, custom mapper, custom idp, custom realm extension, might add extra config. If we want to support any custom keycloak extension/spi, we need these extra config.
In all keycloak projects i work on  I have custom idps and other custom parts for which I highly depend on being able to set extra config. Also see the explicit test in this projec to set dummyConfig and dummyValue on an idp.

On top of that, because of extra config, we can also support immediately any new field keycloak adds without anyone making any code changes, of need to upgrade this provider.(Imagine any other blocking issue, that keeps them from upgrading)

I think we only need to mention in release notes, which new fields were added so that projects that update to a new version of the provider, know what they need change. And perhaps throw an error in the provider when we find a parameter in the extra config that corresponds to explicitly defined field in the resource

**Comment by dmeyerholt** [comment]
@tomrutsaert i'm backing your point here regarding removal of the extra data. we also have some custom idp providers relying on that feature. it should stay regarding the flexibility of this provider. however great that there will be a fix soon. thanks all.
