### ISSUE TITLE
keycloak_custom_identity_provider_mapper does not forward specified config

### ISSUE THREAD

**Issue by msvechla** [mrparkers/terraform-provider-keycloak#561]
Hello

I am trying to use the default `hardcoded-attribute-idp-mapper` via `keycloak_custom_identity_provider_mapper`:

```hcl
resource "keycloak_custom_identity_provider_mapper" "target_idp" {
  realm                    = "broker"
  name                     = "targetIdp"
  identity_provider_alias  = keycloak_oidc_identity_provider.test.alias
  identity_provider_mapper = "hardcoded-attribute-idp-mapper"

  extra_config = {
    "syncMode"        = "FORCE"
    "attribute"       = "targetIdp"
    "attribute.value" = "myval"
  }
}
```

Unfortunately, neither `attribute` nor `attribute.value` are sent to keycloak.

This is confirmed when looking at the terraform trace log:

```
2021-07-21T18:13:49.058+0200 [INFO]  plugin.terraform-provider-keycloak: 2021/07/21 18:13:49 [DEBUG] Sending PUT to /auth/admin/realms/broker/identity-provider/instances/test/mappers/5074a1c5-9896-4c1a-bb4e-090dd5cfd4ca: timestamp=2021-07-21T18:13:49.057+0200
2021-07-21T18:13:49.058+0200 [INFO]  plugin.terraform-provider-keycloak: 2021/07/21 18:13:49 [DEBUG] Request body: {"id":"5074a1c5-9896-4c1a-bb4e-090dd5cfd4ca","name":"targetIdp","identityProviderAlias":"test","identityProviderMapper":"hardcoded-attribute-idp-mapper","config":{"attribute":"","attribute.friendly.name":"","attribute.name":"","attribute.value":"","claim":"","claim.value":"","jsonField":"","role":"","syncMode":"FORCE","template":"","user.attribute":"","userAttribute":""}}: timestamp=2021-07-21T18:13:49.057+0200
2021-07-21T18:13:49.099+0200 [INFO]  plugin.terraform-provider-keycloak: 2021/07/21 18:13:49 [DEBUG] Response: 204 No Content: timestamp=2021-07-21T18:13:49.099+0200
```

Am I doing something wrong on my end or is this a bug?

Thanks for this awesome terraform provider!

**Comment by SJrX** [comment]
Hi @msvechla I had a similar problem to yours so I decided to dig into the code. I think the reason is that you can't override attributes that are actively declared in the IdentityProviderMapperConfig type https://github.com/mrparkers/terraform-provider-keycloak/blob/master/keycloak/identity_provider_mapper.go#L12 .

Unfortunately, there is no way to actually specify those types with the `keycloak_custom_identity_provider_mapper` is my guess. _However_ there do seem to be a lot more resources in the latest version than is documented. So for the above I think you could try:

```
resource "keycloak_hardcoded_attribute_identity_provider_mapper" "target_idp" {
  realm = keycloak_realm.master.id
  name = "foo"
  identity_provider_alias = keycloak_oidc_identity_provider.master_realm_oidc_identity_provider.alias
  extra_config = {
    syncMode = "FORCE"
  }
  attribute_name = "targetIdp"
  attribute_value = "myVal"
  user_session = false
}
```

That seems to work against keycloak 13 with version 3.2.0.

I'm not sure what user_session is for, as I don't see it in the UI.

**Comment by msvechla** [comment]
Thanks for the info @SJrX I already tried something similar, but it does not work, as those attributes are not exposed via terraform:

```
Error: Unsupported argument

  on broker_federation.tf line 24, in resource "keycloak_custom_identity_provider_mapper" "target_idp":
  24:   attribute_name           = "targetIdp"

An argument named "attribute_name" is not expected here.
```

So I think this will have to be fixed in the code

**Comment by tomrutsaert** [comment]
@msvechla underlying both keycloak_hardcoded_attribute_identity_provider_mapper and keycloak_custom_identity_provider_mapper use the same logic that does the check on the fields I assume.
You should use keycloak_hardcoded_attribute_identity_provider_mapper instead of keycloak_custom_identity_provider_mapper

@SJrX  user_session = true  is to make a hardcoded session note mapper (I could be wrong)

@mrparkers  just like on the other location we should show a warning or throw an error when the extra_config contains a param that is already mapped by the logic....

**Comment by msvechla** [comment]
Thanks a lot, my mistake. Using the correct resource works.
I was simply confused because this resource is undocumented and I could not find it in the code at a first glance.

Thanks for the support, I will close this issue then.
