### ISSUE TITLE
Roles not mapping correctly to user

### ISSUE THREAD

**Issue by gerethd** [mrparkers/terraform-provider-keycloak#676]
given the following terraform

```
data keycloak_role roles {
  for_each = toset(concat(var.roles, ["default-roles-zevrant-services-${var.environment}"]))
  realm_id = var.realm_id
  name = each.value
}

resource keycloak_user_roles user_roles {
  for_each = data.keycloak_role.roles
  realm_id = var.realm_id
  user_id = keycloak_user.user.id
  role_ids = [each.value.id]
}
```
where the value of var.roles is the array `[ "backups", "notifications" ]` I'm seeing inconsistent results regarding the state of keycloak after an apply. The first apply i get the backups and default realm role applied, the second apply i get backups and notifications the third time I get notification and default, ... after about 15 ish applies i can finally get the correct set of roles applied.

Running docker.io/jboss/keycloak:16.1.1

**Comment by mrparkers** [comment]
Hi @gerethd, sorry that you've ran into this issue.  It looks like you're trying to assign multiple roles to a single user within Keycloak.  The `keycloak_user_roles` resource should work for this, but not in the way you're currently trying to use it.  The problem here is that the `keycloak_user_roles` resource wants to be an authoritative source for role assignments - meaning that it will attempt to remove any assigned roles that are not in that list, and add assignments for roles in the list if they don't already exist.  This means that multiple instances of `keycloak_user_roles` for the same user will fight with each other, which is why you're running into this issue.

To solve this, I recommend removing the `for_each` meta argument within the `keycloak_user_roles` resource, and instead use a `for` expression to aggregate all of the role IDs from the data source as an input to the `role_ids` argument.  Here's what I think it would look like:

```hcl
data keycloak_role roles {
  for_each = toset(concat(var.roles, ["default-roles-zevrant-services-${var.environment}"]))
  realm_id = var.realm_id
  name = each.value
}

resource keycloak_user_roles user_roles {
  realm_id = var.realm_id
  user_id = keycloak_user.user.id
  role_ids = [for role in data.keycloak_role.roles : role.id]
}
```

I'm going to close this because I verified that this works on my end, but feel free to re-open this if you're still having issues.  Thanks!
