### ISSUE TITLE
Provider should support data sources

### ISSUE THREAD

**Issue by fabienberteau** [mrparkers/terraform-provider-keycloak#69]
In order to read Keycloak generated credentials, provider should support data source on client and user.

**Comment by mrparkers** [comment]
Hi @fabienberteau, thanks for the suggestion!  I definitely want to support data sources that can be used to query information for manually configured resources.

Could you help me understand what your particular use case here is?  I understand wanting a `keycloak_openid_client` data source in order to programmatically retrieve the client secret, but what were you hoping to accomplish with a data source for a user?

Also, could you provide some input on what you think these data sources should look like?

Thanks!

**Comment by mrparkers** [comment]
The two data sources originally requested have since been implemented, so I think this issue can be closed.
