### ISSUE TITLE
Base path environment variable is missing

### ISSUE THREAD

**Issue by markusheiden** [mrparkers/terraform-provider-keycloak#693]
At least for `make testacc` I need to set the base path via environment variable because we use "" as the base path and the test always defaults to "/auth".

So I wasn't able to determine whether my configuration of the provider is wrong or the provider does not support KeyCloak 18.

**Comment by mrparkers** [comment]
Thanks for the issue @markusheiden.  I haven't messed around with the quarkus distribution of Keycloak much yet, and this is the version that removes the `/auth` from the API path.  But you're right, the provider should support configuring this as an environment variable to make this easier.  I've opened #695 to fix this.

In the future, I'll update all of the defaults of this provider to be compatible with the quarkus distribution instead of the legacy wildfly distribution, and I'll publish that as a breaking change (v4.0.0).  But until then, this argument will have to be specified for quarkus users.
