### ISSUE TITLE
Support Retry for initial_login

### ISSUE THREAD

**Issue by damoshushu** [mrparkers/terraform-provider-keycloak#719]
We deploy Keycloak using Helm, then "terraform-provider-keycloak" to create the realm.
And we had set a delay of "60" seconds for terraform-provider-keycloak to initiate.
However, sometimes keycload instance takes more than 60 to be ready, which will lead terraform-provider-keycloak initiation to be failed.

Can we add a retry for terraform-provider-keycloak initiation?

**Comment by mrparkers** [comment]
Hi @damoshushu, thanks for opening this issue.  I've had this issue before, it's actually the main reason why the `initial_login` provider attribute exists.

Unfortunately, I don't think it's possible to add a delay within the Keycloak provider to account for this.  The reason is that Terraform wants its `plan` operation to happen quickly, or at least it doesn't want a plan for a resource taking up to 60 seconds.

In my experience, using codecentric's Keycloak chart (https://github.com/codecentric/helm-charts/tree/master/charts/keycloak), you should be able to set `wait = true` on your `helm_release` terraform resource, and it should be able to properly wait until it's fully online, after which the Keycloak provider should just work.

I'm going to close this for now, but feel free to reply here if you need some help debugging your terraform / helm setup.
