### ISSUE TITLE
Upload provider plugin releases to open domain to allow unauthenticated downloads

### ISSUE THREAD

**Issue by kristofmartens** [mrparkers/terraform-provider-keycloak#99]
It is not possible to download the releases as a machine user without github credentials. Would it be possible to also upload the artifacts to an official S3 bucket where the plugin can be downloaded freely without credentials. This is necessary for building docker images in our CI/CD system that require unauthenticated access to these artifacts.

**Comment by mrparkers** [comment]
Hi @kristofmartens, thanks for the issue.  I have no problem with doing this, but are you sure that authentication is required in order to download releases?  I ask because the Docker image that I use in my pipeline can be built without requiring authentication to GitHub:

```Dockerfile
FROM hashicorp/terraform:0.11.11

ENV TERRAFORM_PROVIDER_KEYCLOAK_VERSION "1.5.0"

RUN mkdir -p ~/.terraform.d/plugins && \
    wget -O terraform-provider-keycloak.zip https://github.com/mrparkers/terraform-provider-keycloak/releases/download/${TERRAFORM_PROVIDER_KEYCLOAK_VERSION}/terraform-provider-keycloak_v${TERRAFORM_PROVIDER_KEYCLOAK_VERSION}_linux_amd64.zip && \
    unzip terraform-provider-keycloak.zip && \
    mv terraform-provider-keycloak_v${TERRAFORM_PROVIDER_KEYCLOAK_VERSION} ~/.terraform.d/plugins && \
    rm terraform-provider-keycloak.zip
```

Could you give something like that a try and let me know if it works for you?  If not, I'm happy to upload releases somewhere else as well.

Thanks!

**Comment by kristofmartens** [comment]
Wget indeed did the trick. Got failures with curl for some reasons.
Thanks for the fast response!

**Comment by mrparkers** [comment]
Happy to help! `curl` should also work as long as you are following redirects, since GitHub themselves stores release binaries in a S3 bucket:

```
curl -LO https://github.com/mrparkers/terraform-provider-keycloak/releases/download/1.5.0/terraform-provider-keycloak_v1.5.0_linux_amd64.zip
```
